/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pigmonitor.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    public Vista() {
        initComponents(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        lotePanel = new javax.swing.JPanel();
        loteLabel = new javax.swing.JLabel();
        pesoLoteTextField = new javax.swing.JTextField();
        pesoLoteLabel = new javax.swing.JLabel();
        numMachosTextField = new javax.swing.JTextField();
        numMachosLabel = new javax.swing.JLabel();
        numHembrasTextField = new javax.swing.JTextField();
        numHembrasLabel = new javax.swing.JLabel();
        codigoLoteTextField = new javax.swing.JTextField();
        numLoteLabel = new javax.swing.JLabel();
        buscarLoteButton = new javax.swing.JButton();
        guardarLoteButton = new javax.swing.JButton();
        modificarLoteButton = new javax.swing.JButton();
        eliminarLoteButton = new javax.swing.JButton();
        limpiarLoteButton = new javax.swing.JButton();
        idLoteTextField = new javax.swing.JTextField();
        enfermedadPanel = new javax.swing.JPanel();
        enfermedadLabel = new javax.swing.JLabel();
        codigoEnfermedadLabel = new javax.swing.JLabel();
        nombreEnfermedadLabel = new javax.swing.JLabel();
        numCerdosAfectLabel = new javax.swing.JLabel();
        idEnfermedadTextField = new javax.swing.JTextField();
        codigoEnfermedadTextField = new javax.swing.JTextField();
        nombreEnfermedadTextField = new javax.swing.JTextField();
        numCerdosAfectTextField = new javax.swing.JTextField();
        guardarEnfermedadButton = new javax.swing.JButton();
        modificarEnfermedadButton = new javax.swing.JButton();
        eliminarEnfermedadButton = new javax.swing.JButton();
        limpiarEnfermedadButton = new javax.swing.JButton();
        buscarEnfermedadButton = new javax.swing.JButton();
        alimentoPanel = new javax.swing.JPanel();
        alimentoLabel = new javax.swing.JLabel();
        idAlimentoLabel = new javax.swing.JLabel();
        nombreAlimentoLabel = new javax.swing.JLabel();
        numBultosLabel = new javax.swing.JLabel();
        precioAlimentoLabel = new javax.swing.JLabel();
        codigoAlimentoTextField = new javax.swing.JTextField();
        nombreAlimentoTextField = new javax.swing.JTextField();
        numBultosTextField = new javax.swing.JTextField();
        precioAlimentoTextField = new javax.swing.JTextField();
        buscarAlimentoButton = new javax.swing.JButton();
        idAlimentoTextField = new javax.swing.JTextField();
        guardarAlimentoButton = new javax.swing.JButton();
        modificarAlimentoButton = new javax.swing.JButton();
        eliminarAlimentoButton = new javax.swing.JButton();
        limpiarAlimentoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loteLabel.setText("Entrada de Datos");

        pesoLoteLabel.setText("Ingrese el Peso Promedio del Lote");

        numMachosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMachosTextFieldActionPerformed(evt);
            }
        });

        numMachosLabel.setText("Ingrese el Numero de Machos");

        numHembrasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numHembrasTextFieldActionPerformed(evt);
            }
        });

        numHembrasLabel.setText("Ingrese el Numero de Hembras");

        numLoteLabel.setText("Ingrese el Numero del Lote");

        buscarLoteButton.setText("Buscar");

        guardarLoteButton.setText("Guardar");

        modificarLoteButton.setText("Modificar");

        eliminarLoteButton.setText("Eliminar");

        limpiarLoteButton.setText("Limpiar");

        javax.swing.GroupLayout lotePanelLayout = new javax.swing.GroupLayout(lotePanel);
        lotePanel.setLayout(lotePanelLayout);
        lotePanelLayout.setHorizontalGroup(
            lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lotePanelLayout.createSequentialGroup()
                .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lotePanelLayout.createSequentialGroup()
                        .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lotePanelLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(loteLabel))
                            .addGroup(lotePanelLayout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(modificarLoteButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(lotePanelLayout.createSequentialGroup()
                        .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lotePanelLayout.createSequentialGroup()
                                .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(lotePanelLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(guardarLoteButton)
                                        .addGap(252, 252, 252)
                                        .addComponent(eliminarLoteButton))
                                    .addGroup(lotePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(numLoteLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lotePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(pesoLoteLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pesoLoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lotePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lotePanelLayout.createSequentialGroup()
                                        .addComponent(numHembrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numHembrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lotePanelLayout.createSequentialGroup()
                                        .addComponent(numMachosLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numMachosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lotePanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(codigoLoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarLoteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLoteTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limpiarLoteButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        lotePanelLayout.setVerticalGroup(
            lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lotePanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(loteLabel)
                .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lotePanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoLoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numLoteLabel))
                        .addGap(25, 25, 25)
                        .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numHembrasLabel)
                            .addComponent(numHembrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numMachosLabel)
                            .addComponent(numMachosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoLoteLabel)
                            .addComponent(pesoLoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardarLoteButton)
                            .addGroup(lotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modificarLoteButton)
                                .addComponent(eliminarLoteButton))
                            .addComponent(limpiarLoteButton)))
                    .addGroup(lotePanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(buscarLoteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idLoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane1.addTab("Lote", lotePanel);

        enfermedadLabel.setText("Entrada de Datos");

        codigoEnfermedadLabel.setText("Ingrese el Numero de la Enfermedad");

        nombreEnfermedadLabel.setText("Ingrese el Nombre de la Enfermedad");

        numCerdosAfectLabel.setText("Ingrese el Numero de Cerdos Afectados");

        codigoEnfermedadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoEnfermedadTextFieldActionPerformed(evt);
            }
        });

        guardarEnfermedadButton.setText("Guardar");
        guardarEnfermedadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEnfermedadButtonActionPerformed(evt);
            }
        });

        modificarEnfermedadButton.setText("Modificar");
        modificarEnfermedadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEnfermedadButtonActionPerformed(evt);
            }
        });

        eliminarEnfermedadButton.setText("Eliminar");
        eliminarEnfermedadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEnfermedadButtonActionPerformed(evt);
            }
        });

        limpiarEnfermedadButton.setText("Limpiar");

        buscarEnfermedadButton.setText("Buscar");

        javax.swing.GroupLayout enfermedadPanelLayout = new javax.swing.GroupLayout(enfermedadPanel);
        enfermedadPanel.setLayout(enfermedadPanelLayout);
        enfermedadPanelLayout.setHorizontalGroup(
            enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enfermedadPanelLayout.createSequentialGroup()
                .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enfermedadPanelLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(enfermedadLabel))
                    .addGroup(enfermedadPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(numCerdosAfectLabel)
                        .addGap(48, 48, 48)
                        .addComponent(numCerdosAfectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(enfermedadPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enfermedadPanelLayout.createSequentialGroup()
                        .addComponent(nombreEnfermedadLabel)
                        .addGap(65, 65, 65)
                        .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigoEnfermedadTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(nombreEnfermedadTextField)))
                    .addComponent(codigoEnfermedadLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarEnfermedadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idEnfermedadTextField))
                .addGap(31, 31, 31))
            .addGroup(enfermedadPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(guardarEnfermedadButton)
                .addGap(45, 45, 45)
                .addComponent(modificarEnfermedadButton)
                .addGap(56, 56, 56)
                .addComponent(eliminarEnfermedadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limpiarEnfermedadButton)
                .addGap(43, 43, 43))
        );
        enfermedadPanelLayout.setVerticalGroup(
            enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enfermedadPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(enfermedadLabel)
                .addGap(51, 51, 51)
                .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoEnfermedadLabel)
                    .addComponent(codigoEnfermedadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarEnfermedadButton))
                .addGap(22, 22, 22)
                .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreEnfermedadLabel)
                    .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombreEnfermedadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idEnfermedadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numCerdosAfectLabel)
                    .addComponent(numCerdosAfectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(enfermedadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarEnfermedadButton)
                    .addComponent(modificarEnfermedadButton)
                    .addComponent(eliminarEnfermedadButton)
                    .addComponent(limpiarEnfermedadButton))
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Enfermedad", enfermedadPanel);

        alimentoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alimentoLabel.setText("Entrada de Datos");
        alimentoPanel.add(alimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        idAlimentoLabel.setText("Ingrese el Numero de Alimento");
        alimentoPanel.add(idAlimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        nombreAlimentoLabel.setText("Ingrese el Nombre del alimento ");
        alimentoPanel.add(nombreAlimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        numBultosLabel.setText("Ingrese el Numero de Bultos");
        alimentoPanel.add(numBultosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        precioAlimentoLabel.setText("Ingrese el Precio Total");
        alimentoPanel.add(precioAlimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        codigoAlimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoAlimentoTextFieldActionPerformed(evt);
            }
        });
        alimentoPanel.add(codigoAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 90, -1));

        nombreAlimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAlimentoTextFieldActionPerformed(evt);
            }
        });
        alimentoPanel.add(nombreAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 90, -1));
        alimentoPanel.add(numBultosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, -1));

        precioAlimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioAlimentoTextFieldActionPerformed(evt);
            }
        });
        alimentoPanel.add(precioAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, -1));

        buscarAlimentoButton.setText("Buscar");
        buscarAlimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlimentoButtonActionPerformed(evt);
            }
        });
        alimentoPanel.add(buscarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 80, -1));
        alimentoPanel.add(idAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 80, -1));

        guardarAlimentoButton.setText("Guardar");
        guardarAlimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAlimentoButtonActionPerformed(evt);
            }
        });
        alimentoPanel.add(guardarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        modificarAlimentoButton.setText("Modificar");
        modificarAlimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAlimentoButtonActionPerformed(evt);
            }
        });
        alimentoPanel.add(modificarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        eliminarAlimentoButton.setText("Eliminar");
        eliminarAlimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAlimentoButtonActionPerformed(evt);
            }
        });
        alimentoPanel.add(eliminarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        limpiarAlimentoButton.setText("Limpiar");
        limpiarAlimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarAlimentoButtonActionPerformed(evt);
            }
        });
        alimentoPanel.add(limpiarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        jTabbedPane1.addTab("Alimento", alimentoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoAlimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoAlimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoAlimentoTextFieldActionPerformed

    private void nombreAlimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAlimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAlimentoTextFieldActionPerformed

    private void precioAlimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioAlimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioAlimentoTextFieldActionPerformed

    private void eliminarEnfermedadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEnfermedadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarEnfermedadButtonActionPerformed

    private void guardarEnfermedadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEnfermedadButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_guardarEnfermedadButtonActionPerformed

    private void numHembrasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numHembrasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numHembrasTextFieldActionPerformed

    private void numMachosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMachosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMachosTextFieldActionPerformed

    private void modificarEnfermedadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEnfermedadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarEnfermedadButtonActionPerformed

    private void codigoEnfermedadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoEnfermedadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEnfermedadTextFieldActionPerformed

    private void limpiarAlimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarAlimentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarAlimentoButtonActionPerformed

    private void guardarAlimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAlimentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarAlimentoButtonActionPerformed

    private void modificarAlimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAlimentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarAlimentoButtonActionPerformed

    private void eliminarAlimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAlimentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarAlimentoButtonActionPerformed

    private void buscarAlimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlimentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarAlimentoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alimentoLabel;
    private javax.swing.JPanel alimentoPanel;
    public javax.swing.JButton buscarAlimentoButton;
    public javax.swing.JButton buscarEnfermedadButton;
    public javax.swing.JButton buscarLoteButton;
    public javax.swing.JTextField codigoAlimentoTextField;
    private javax.swing.JLabel codigoEnfermedadLabel;
    public javax.swing.JTextField codigoEnfermedadTextField;
    public javax.swing.JTextField codigoLoteTextField;
    public javax.swing.JButton eliminarAlimentoButton;
    public javax.swing.JButton eliminarEnfermedadButton;
    public javax.swing.JButton eliminarLoteButton;
    private javax.swing.JLabel enfermedadLabel;
    private javax.swing.JPanel enfermedadPanel;
    public javax.swing.JButton guardarAlimentoButton;
    public javax.swing.JButton guardarEnfermedadButton;
    public javax.swing.JButton guardarLoteButton;
    private javax.swing.JLabel idAlimentoLabel;
    public javax.swing.JTextField idAlimentoTextField;
    public javax.swing.JTextField idEnfermedadTextField;
    public javax.swing.JTextField idLoteTextField;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton limpiarAlimentoButton;
    public javax.swing.JButton limpiarEnfermedadButton;
    public javax.swing.JButton limpiarLoteButton;
    private javax.swing.JLabel loteLabel;
    private javax.swing.JPanel lotePanel;
    public javax.swing.JButton modificarAlimentoButton;
    public javax.swing.JButton modificarEnfermedadButton;
    public javax.swing.JButton modificarLoteButton;
    private javax.swing.JLabel nombreAlimentoLabel;
    public javax.swing.JTextField nombreAlimentoTextField;
    private javax.swing.JLabel nombreEnfermedadLabel;
    public javax.swing.JTextField nombreEnfermedadTextField;
    private javax.swing.JLabel numBultosLabel;
    public javax.swing.JTextField numBultosTextField;
    private javax.swing.JLabel numCerdosAfectLabel;
    public javax.swing.JTextField numCerdosAfectTextField;
    private javax.swing.JLabel numHembrasLabel;
    public javax.swing.JTextField numHembrasTextField;
    private javax.swing.JLabel numLoteLabel;
    private javax.swing.JLabel numMachosLabel;
    public javax.swing.JTextField numMachosTextField;
    private javax.swing.JLabel pesoLoteLabel;
    public javax.swing.JTextField pesoLoteTextField;
    private javax.swing.JLabel precioAlimentoLabel;
    public javax.swing.JTextField precioAlimentoTextField;
    // End of variables declaration//GEN-END:variables
}
