/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pigmonitor.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    public Vista() {
        initComponents(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        lotePanel = new javax.swing.JPanel();
        loteLabel = new javax.swing.JLabel();
        pesoLoteTextField = new javax.swing.JTextField();
        pesoLoteLabel = new javax.swing.JLabel();
        numMachosTextField = new javax.swing.JTextField();
        numMachosLabel = new javax.swing.JLabel();
        numHembrasTextField = new javax.swing.JTextField();
        numHembrasLabel = new javax.swing.JLabel();
        codigoLoteTextField = new javax.swing.JTextField();
        numLoteLabel = new javax.swing.JLabel();
        buscarLoteButton = new javax.swing.JButton();
        guardarLoteButton = new javax.swing.JButton();
        modificarLoteButton = new javax.swing.JButton();
        eliminarLoteButton = new javax.swing.JButton();
        limpiarLoteButton = new javax.swing.JButton();
        idLoteTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Alimento_idAlimento = new javax.swing.JLabel();
        alimento_idAlimentoTextField = new javax.swing.JTextField();
        medicamento_idMedicamentoTextField = new javax.swing.JTextField();
        Medicamento_idMedicamento = new javax.swing.JLabel();
        loteEnfermedadTextField = new javax.swing.JTextField();
        loteEnfermedadLabel = new javax.swing.JLabel();
        LoteInsumoLabel = new javax.swing.JLabel();
        loteInsumosTextField = new javax.swing.JTextField();
        loteEnfermedadButton = new javax.swing.JButton();
        loteInsumoButton = new javax.swing.JButton();
        enfermedadPanel = new javax.swing.JPanel();
        enfermedadLabel = new javax.swing.JLabel();
        codigoEnfermedadLabel = new javax.swing.JLabel();
        nombreEnfermedadLabel = new javax.swing.JLabel();
        numCerdosAfectLabel = new javax.swing.JLabel();
        idEnfermedadTextField = new javax.swing.JTextField();
        codigoEnfermedadTextField = new javax.swing.JTextField();
        nombreEnfermedadTextField = new javax.swing.JTextField();
        numCerdosAfectTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guardarEnfermedadButton = new javax.swing.JButton();
        modificarEnfermedadButton = new javax.swing.JButton();
        eliminarEnfermedadButton = new javax.swing.JButton();
        limpiarEnfermedadButton = new javax.swing.JButton();
        buscarEnfermedadButton = new javax.swing.JButton();
        alimentoPanel = new javax.swing.JPanel();
        alimentoLabel = new javax.swing.JLabel();
        idAlimentoLabel = new javax.swing.JLabel();
        nombreAlimentoLabel = new javax.swing.JLabel();
        numBultosLabel = new javax.swing.JLabel();
        precioAlimentoLabel = new javax.swing.JLabel();
        codigoAlimentoTextField = new javax.swing.JTextField();
        nombreAlimentoTextField = new javax.swing.JTextField();
        numBultosTextField = new javax.swing.JTextField();
        precioAlimentoTextField = new javax.swing.JTextField();
        idAlimentoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        guardarAlimentoButton = new javax.swing.JButton();
        modificarAlimentoButton = new javax.swing.JButton();
        eliminarAlimentoButton = new javax.swing.JButton();
        limpiarAlimentoButton = new javax.swing.JButton();
        buscarAlimentoButton = new javax.swing.JButton();
        insumoPanel = new javax.swing.JPanel();
        insumosLabel = new javax.swing.JLabel();
        codigoInsumoLabel = new javax.swing.JLabel();
        nombreInsumoLabel = new javax.swing.JLabel();
        precioInsumoLabel = new javax.swing.JLabel();
        precioInsumoTextField = new javax.swing.JTextField();
        codigoInsumoTextField = new javax.swing.JTextField();
        nombreInsumoTextField = new javax.swing.JTextField();
        idInsumoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buscarInsumoButton = new javax.swing.JButton();
        guardarInsumoButton = new javax.swing.JButton();
        modificarInsumoButton = new javax.swing.JButton();
        eliminarInsumoButton = new javax.swing.JButton();
        limpiarInsumosButton = new javax.swing.JButton();
        medicamentoPanel = new javax.swing.JPanel();
        medicamentoLabel = new javax.swing.JLabel();
        codigoMedicamentoLabel = new javax.swing.JLabel();
        nombreMedicamentoLabel = new javax.swing.JLabel();
        numeroExistenciasLabel = new javax.swing.JLabel();
        precioMedicamentoLabel = new javax.swing.JLabel();
        codigoMedicamentoTextField = new javax.swing.JTextField();
        nombreMedicamentoTextField = new javax.swing.JTextField();
        numeroExistenciasTextField = new javax.swing.JTextField();
        precioMedicamentoTextField = new javax.swing.JTextField();
        idMedicamentoTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        guardarMedicamentoButton = new javax.swing.JButton();
        modificarMedicamentoButton = new javax.swing.JButton();
        eliminarMedicamentoButton = new javax.swing.JButton();
        limpiarMedicamentoButton = new javax.swing.JButton();
        buscarMedicamentoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lotePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loteLabel.setText("Entrada de Datos Lote");
        lotePanel.add(loteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));
        lotePanel.add(pesoLoteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 80, -1));

        pesoLoteLabel.setText("Peso Promedio del Lote");
        lotePanel.add(pesoLoteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        numMachosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMachosTextFieldActionPerformed(evt);
            }
        });
        lotePanel.add(numMachosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 80, -1));

        numMachosLabel.setText("Numero de Machos");
        lotePanel.add(numMachosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, -1));

        numHembrasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numHembrasTextFieldActionPerformed(evt);
            }
        });
        lotePanel.add(numHembrasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 80, -1));

        numHembrasLabel.setText("Numero de Hembras");
        lotePanel.add(numHembrasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, -1));
        lotePanel.add(codigoLoteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 101, -1));

        numLoteLabel.setText("Codigo del Lote");
        lotePanel.add(numLoteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 190, -1));

        buscarLoteButton.setBackground(new java.awt.Color(162, 251, 220));
        buscarLoteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_30px.png"))); // NOI18N
        buscarLoteButton.setText("Buscar");
        buscarLoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLoteButtonActionPerformed(evt);
            }
        });
        lotePanel.add(buscarLoteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, -1));

        guardarLoteButton.setBackground(new java.awt.Color(153, 255, 153));
        guardarLoteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_lock_30px.png"))); // NOI18N
        guardarLoteButton.setText(" Guardar");
        guardarLoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarLoteButtonActionPerformed(evt);
            }
        });
        lotePanel.add(guardarLoteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 50));

        modificarLoteButton.setBackground(new java.awt.Color(204, 247, 242));
        modificarLoteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_property_30px.png"))); // NOI18N
        modificarLoteButton.setText(" Modificar");
        lotePanel.add(modificarLoteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 140, 50));

        eliminarLoteButton.setBackground(new java.awt.Color(255, 102, 102));
        eliminarLoteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_30px.png"))); // NOI18N
        eliminarLoteButton.setText(" Eliminar");
        lotePanel.add(eliminarLoteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, 50));

        limpiarLoteButton.setBackground(new java.awt.Color(255, 255, 204));
        limpiarLoteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/broom_30px.png"))); // NOI18N
        limpiarLoteButton.setText(" Limpiar");
        limpiarLoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarLoteButtonActionPerformed(evt);
            }
        });
        lotePanel.add(limpiarLoteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 120, 50));

        idLoteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idLoteTextFieldActionPerformed(evt);
            }
        });
        lotePanel.add(idLoteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 70, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minilogo.png"))); // NOI18N
        lotePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        Alimento_idAlimento.setText("Codigo del Alimento del Lote");
        lotePanel.add(Alimento_idAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        alimento_idAlimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimento_idAlimentoTextFieldActionPerformed(evt);
            }
        });
        lotePanel.add(alimento_idAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, -1));

        medicamento_idMedicamentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamento_idMedicamentoTextFieldActionPerformed(evt);
            }
        });
        lotePanel.add(medicamento_idMedicamentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 70, -1));

        Medicamento_idMedicamento.setText("Codigo del Medicamento del Lote");
        lotePanel.add(Medicamento_idMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 220, -1));
        lotePanel.add(loteEnfermedadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 70, -1));

        loteEnfermedadLabel.setText("Codigo de las Enfermedades de Lote");
        lotePanel.add(loteEnfermedadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 210, -1));

        LoteInsumoLabel.setText("Codigo de los Insumos que Consume");
        lotePanel.add(LoteInsumoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 200, -1));
        lotePanel.add(loteInsumosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 70, -1));

        loteEnfermedadButton.setText("Agregar Enfermedad");
        lotePanel.add(loteEnfermedadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 160, -1));

        loteInsumoButton.setText("Agregar Insumo");
        loteInsumoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loteInsumoButtonActionPerformed(evt);
            }
        });
        lotePanel.add(loteInsumoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 130, -1));

        jTabbedPane1.addTab("Lote", lotePanel);

        enfermedadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enfermedadLabel.setText("Entrada de Datos de Enfermedad");
        enfermedadPanel.add(enfermedadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        codigoEnfermedadLabel.setText("Codigo de la Enfermedad");
        enfermedadPanel.add(codigoEnfermedadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        nombreEnfermedadLabel.setText("Nombre de la Enfermedad");
        enfermedadPanel.add(nombreEnfermedadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        numCerdosAfectLabel.setText("Numero de Cerdos Afectados");
        enfermedadPanel.add(numCerdosAfectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));
        enfermedadPanel.add(idEnfermedadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 65, -1));

        codigoEnfermedadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoEnfermedadTextFieldActionPerformed(evt);
            }
        });
        enfermedadPanel.add(codigoEnfermedadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 90, -1));
        enfermedadPanel.add(nombreEnfermedadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 90, -1));
        enfermedadPanel.add(numCerdosAfectTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minilogo.png"))); // NOI18N
        enfermedadPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        guardarEnfermedadButton.setBackground(new java.awt.Color(153, 255, 153));
        guardarEnfermedadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_lock_30px.png"))); // NOI18N
        guardarEnfermedadButton.setText(" Guardar");
        guardarEnfermedadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEnfermedadButtonActionPerformed(evt);
            }
        });
        enfermedadPanel.add(guardarEnfermedadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 50));

        modificarEnfermedadButton.setBackground(new java.awt.Color(204, 247, 242));
        modificarEnfermedadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_property_30px.png"))); // NOI18N
        modificarEnfermedadButton.setText(" Modificar");
        enfermedadPanel.add(modificarEnfermedadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 140, 50));

        eliminarEnfermedadButton.setBackground(new java.awt.Color(255, 102, 102));
        eliminarEnfermedadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_30px.png"))); // NOI18N
        eliminarEnfermedadButton.setText(" Eliminar");
        enfermedadPanel.add(eliminarEnfermedadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, 50));

        limpiarEnfermedadButton.setBackground(new java.awt.Color(255, 255, 204));
        limpiarEnfermedadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/broom_30px.png"))); // NOI18N
        limpiarEnfermedadButton.setText(" Limpiar");
        limpiarEnfermedadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarEnfermedadButtonActionPerformed(evt);
            }
        });
        enfermedadPanel.add(limpiarEnfermedadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 120, 50));

        buscarEnfermedadButton.setBackground(new java.awt.Color(162, 251, 220));
        buscarEnfermedadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_30px.png"))); // NOI18N
        buscarEnfermedadButton.setText("Buscar");
        buscarEnfermedadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEnfermedadButtonActionPerformed(evt);
            }
        });
        enfermedadPanel.add(buscarEnfermedadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 110, -1));

        jTabbedPane1.addTab("Enfermedad", enfermedadPanel);

        alimentoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alimentoLabel.setText("Entrada de Datos de Alimentos");
        alimentoPanel.add(alimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        idAlimentoLabel.setText("Codigo de Alimento");
        alimentoPanel.add(idAlimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        nombreAlimentoLabel.setText("Nombre del alimento ");
        alimentoPanel.add(nombreAlimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        numBultosLabel.setText("Numero de Bultos");
        alimentoPanel.add(numBultosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        precioAlimentoLabel.setText("Precio Total");
        alimentoPanel.add(precioAlimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        codigoAlimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoAlimentoTextFieldActionPerformed(evt);
            }
        });
        alimentoPanel.add(codigoAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 90, -1));

        nombreAlimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAlimentoTextFieldActionPerformed(evt);
            }
        });
        alimentoPanel.add(nombreAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 90, -1));
        alimentoPanel.add(numBultosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 90, -1));

        precioAlimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioAlimentoTextFieldActionPerformed(evt);
            }
        });
        alimentoPanel.add(precioAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 90, -1));
        alimentoPanel.add(idAlimentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 80, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minilogo.png"))); // NOI18N
        alimentoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        guardarAlimentoButton.setBackground(new java.awt.Color(153, 255, 153));
        guardarAlimentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_lock_30px.png"))); // NOI18N
        guardarAlimentoButton.setText(" Guardar");
        guardarAlimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAlimentoButtonActionPerformed(evt);
            }
        });
        alimentoPanel.add(guardarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 50));

        modificarAlimentoButton.setBackground(new java.awt.Color(204, 247, 242));
        modificarAlimentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_property_30px.png"))); // NOI18N
        modificarAlimentoButton.setText(" Modificar");
        alimentoPanel.add(modificarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 140, 50));

        eliminarAlimentoButton.setBackground(new java.awt.Color(255, 102, 102));
        eliminarAlimentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_30px.png"))); // NOI18N
        eliminarAlimentoButton.setText(" Eliminar");
        alimentoPanel.add(eliminarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, 50));

        limpiarAlimentoButton.setBackground(new java.awt.Color(255, 255, 204));
        limpiarAlimentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/broom_30px.png"))); // NOI18N
        limpiarAlimentoButton.setText(" Limpiar");
        limpiarAlimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarAlimentoButtonActionPerformed(evt);
            }
        });
        alimentoPanel.add(limpiarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 120, 50));

        buscarAlimentoButton.setBackground(new java.awt.Color(162, 251, 220));
        buscarAlimentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_30px.png"))); // NOI18N
        buscarAlimentoButton.setText("Buscar");
        buscarAlimentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlimentoButtonActionPerformed(evt);
            }
        });
        alimentoPanel.add(buscarAlimentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 110, -1));

        jTabbedPane1.addTab("Alimento", alimentoPanel);

        insumoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insumosLabel.setText("Entrada de Datos de Insumos");
        insumoPanel.add(insumosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        codigoInsumoLabel.setText("Codigo de Insumo");
        insumoPanel.add(codigoInsumoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        nombreInsumoLabel.setText("Nombre de Insumo");
        insumoPanel.add(nombreInsumoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        precioInsumoLabel.setText("Precio del Insumo");
        insumoPanel.add(precioInsumoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));
        insumoPanel.add(precioInsumoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 130, -1));
        insumoPanel.add(codigoInsumoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 130, -1));
        insumoPanel.add(nombreInsumoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 130, -1));
        insumoPanel.add(idInsumoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 60, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minilogo.png"))); // NOI18N
        insumoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        buscarInsumoButton.setBackground(new java.awt.Color(162, 251, 220));
        buscarInsumoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_30px.png"))); // NOI18N
        buscarInsumoButton.setText("Buscar");
        buscarInsumoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarInsumoButtonActionPerformed(evt);
            }
        });
        insumoPanel.add(buscarInsumoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 110, -1));

        guardarInsumoButton.setBackground(new java.awt.Color(153, 255, 153));
        guardarInsumoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_lock_30px.png"))); // NOI18N
        guardarInsumoButton.setText(" Guardar");
        guardarInsumoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarInsumoButtonActionPerformed(evt);
            }
        });
        insumoPanel.add(guardarInsumoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 50));

        modificarInsumoButton.setBackground(new java.awt.Color(204, 247, 242));
        modificarInsumoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_property_30px.png"))); // NOI18N
        modificarInsumoButton.setText(" Modificar");
        insumoPanel.add(modificarInsumoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 140, 50));

        eliminarInsumoButton.setBackground(new java.awt.Color(255, 102, 102));
        eliminarInsumoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_30px.png"))); // NOI18N
        eliminarInsumoButton.setText(" Eliminar");
        insumoPanel.add(eliminarInsumoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, 50));

        limpiarInsumosButton.setBackground(new java.awt.Color(255, 255, 204));
        limpiarInsumosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/broom_30px.png"))); // NOI18N
        limpiarInsumosButton.setText(" Limpiar");
        limpiarInsumosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarInsumosButtonActionPerformed(evt);
            }
        });
        insumoPanel.add(limpiarInsumosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 120, 50));

        jTabbedPane1.addTab("Insumos", insumoPanel);

        medicamentoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicamentoLabel.setText("Entrada de Datos de Medicamentos");
        medicamentoPanel.add(medicamentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        codigoMedicamentoLabel.setText("Codigo de Medicamento");
        medicamentoPanel.add(codigoMedicamentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        nombreMedicamentoLabel.setText("Nombre de Medicamento ");
        medicamentoPanel.add(nombreMedicamentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        numeroExistenciasLabel.setText("Numero de Existencias ");
        medicamentoPanel.add(numeroExistenciasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        precioMedicamentoLabel.setText("Precio por Unidad");
        medicamentoPanel.add(precioMedicamentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        codigoMedicamentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoMedicamentoTextFieldActionPerformed(evt);
            }
        });
        medicamentoPanel.add(codigoMedicamentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 110, -1));

        nombreMedicamentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMedicamentoTextFieldActionPerformed(evt);
            }
        });
        medicamentoPanel.add(nombreMedicamentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 110, -1));
        medicamentoPanel.add(numeroExistenciasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 110, -1));

        precioMedicamentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioMedicamentoTextFieldActionPerformed(evt);
            }
        });
        medicamentoPanel.add(precioMedicamentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 110, -1));
        medicamentoPanel.add(idMedicamentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 65, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minilogo.png"))); // NOI18N
        medicamentoPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        guardarMedicamentoButton.setBackground(new java.awt.Color(153, 255, 153));
        guardarMedicamentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check_lock_30px.png"))); // NOI18N
        guardarMedicamentoButton.setText(" Guardar");
        guardarMedicamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMedicamentoButtonActionPerformed(evt);
            }
        });
        medicamentoPanel.add(guardarMedicamentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 50));

        modificarMedicamentoButton.setBackground(new java.awt.Color(204, 247, 242));
        modificarMedicamentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_property_30px.png"))); // NOI18N
        modificarMedicamentoButton.setText(" Modificar");
        medicamentoPanel.add(modificarMedicamentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 140, 50));

        eliminarMedicamentoButton.setBackground(new java.awt.Color(255, 102, 102));
        eliminarMedicamentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_30px.png"))); // NOI18N
        eliminarMedicamentoButton.setText(" Eliminar");
        medicamentoPanel.add(eliminarMedicamentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 120, 50));

        limpiarMedicamentoButton.setBackground(new java.awt.Color(255, 255, 204));
        limpiarMedicamentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/broom_30px.png"))); // NOI18N
        limpiarMedicamentoButton.setText(" Limpiar");
        limpiarMedicamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarMedicamentoButtonActionPerformed(evt);
            }
        });
        medicamentoPanel.add(limpiarMedicamentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 120, 50));

        buscarMedicamentoButton.setBackground(new java.awt.Color(162, 251, 220));
        buscarMedicamentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_30px.png"))); // NOI18N
        buscarMedicamentoButton.setText("Buscar");
        buscarMedicamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMedicamentoButtonActionPerformed(evt);
            }
        });
        medicamentoPanel.add(buscarMedicamentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 110, -1));

        jTabbedPane1.addTab("Medicamento", medicamentoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoAlimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoAlimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoAlimentoTextFieldActionPerformed

    private void nombreAlimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAlimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAlimentoTextFieldActionPerformed

    private void precioAlimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioAlimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioAlimentoTextFieldActionPerformed

    private void numHembrasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numHembrasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numHembrasTextFieldActionPerformed

    private void numMachosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMachosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMachosTextFieldActionPerformed

    private void codigoEnfermedadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoEnfermedadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEnfermedadTextFieldActionPerformed

    private void codigoMedicamentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoMedicamentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoMedicamentoTextFieldActionPerformed

    private void precioMedicamentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioMedicamentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioMedicamentoTextFieldActionPerformed

    private void idLoteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idLoteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idLoteTextFieldActionPerformed

    private void buscarLoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLoteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarLoteButtonActionPerformed

    private void nombreMedicamentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMedicamentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMedicamentoTextFieldActionPerformed

    private void alimento_idAlimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimento_idAlimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alimento_idAlimentoTextFieldActionPerformed

    private void medicamento_idMedicamentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamento_idMedicamentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicamento_idMedicamentoTextFieldActionPerformed

    private void loteInsumoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loteInsumoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loteInsumoButtonActionPerformed

    private void guardarLoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarLoteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarLoteButtonActionPerformed

    private void limpiarLoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarLoteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarLoteButtonActionPerformed

    private void guardarEnfermedadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEnfermedadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarEnfermedadButtonActionPerformed

    private void limpiarEnfermedadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarEnfermedadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarEnfermedadButtonActionPerformed

    private void buscarEnfermedadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEnfermedadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarEnfermedadButtonActionPerformed

    private void guardarAlimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAlimentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarAlimentoButtonActionPerformed

    private void limpiarAlimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarAlimentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarAlimentoButtonActionPerformed

    private void buscarAlimentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlimentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarAlimentoButtonActionPerformed

    private void buscarInsumoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarInsumoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarInsumoButtonActionPerformed

    private void guardarInsumoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarInsumoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarInsumoButtonActionPerformed

    private void limpiarInsumosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarInsumosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarInsumosButtonActionPerformed

    private void guardarMedicamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMedicamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarMedicamentoButtonActionPerformed

    private void limpiarMedicamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarMedicamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarMedicamentoButtonActionPerformed

    private void buscarMedicamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMedicamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMedicamentoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Alimento_idAlimento;
    private javax.swing.JLabel LoteInsumoLabel;
    public javax.swing.JLabel Medicamento_idMedicamento;
    private javax.swing.JLabel alimentoLabel;
    private javax.swing.JPanel alimentoPanel;
    public javax.swing.JTextField alimento_idAlimentoTextField;
    public javax.swing.JButton buscarAlimentoButton;
    public javax.swing.JButton buscarEnfermedadButton;
    public javax.swing.JButton buscarInsumoButton;
    public javax.swing.JButton buscarLoteButton;
    public javax.swing.JButton buscarMedicamentoButton;
    public javax.swing.JTextField codigoAlimentoTextField;
    private javax.swing.JLabel codigoEnfermedadLabel;
    public javax.swing.JTextField codigoEnfermedadTextField;
    private javax.swing.JLabel codigoInsumoLabel;
    public javax.swing.JTextField codigoInsumoTextField;
    public javax.swing.JTextField codigoLoteTextField;
    private javax.swing.JLabel codigoMedicamentoLabel;
    public javax.swing.JTextField codigoMedicamentoTextField;
    public javax.swing.JButton eliminarAlimentoButton;
    public javax.swing.JButton eliminarEnfermedadButton;
    public javax.swing.JButton eliminarInsumoButton;
    public javax.swing.JButton eliminarLoteButton;
    public javax.swing.JButton eliminarMedicamentoButton;
    private javax.swing.JLabel enfermedadLabel;
    private javax.swing.JPanel enfermedadPanel;
    public javax.swing.JButton guardarAlimentoButton;
    public javax.swing.JButton guardarEnfermedadButton;
    public javax.swing.JButton guardarInsumoButton;
    public javax.swing.JButton guardarLoteButton;
    public javax.swing.JButton guardarMedicamentoButton;
    private javax.swing.JLabel idAlimentoLabel;
    public javax.swing.JTextField idAlimentoTextField;
    public javax.swing.JTextField idEnfermedadTextField;
    public javax.swing.JTextField idInsumoTextField;
    public javax.swing.JTextField idLoteTextField;
    public javax.swing.JTextField idMedicamentoTextField;
    private javax.swing.JPanel insumoPanel;
    private javax.swing.JLabel insumosLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton limpiarAlimentoButton;
    public javax.swing.JButton limpiarEnfermedadButton;
    public javax.swing.JButton limpiarInsumosButton;
    public javax.swing.JButton limpiarLoteButton;
    public javax.swing.JButton limpiarMedicamentoButton;
    private javax.swing.JButton loteEnfermedadButton;
    private javax.swing.JLabel loteEnfermedadLabel;
    private javax.swing.JTextField loteEnfermedadTextField;
    private javax.swing.JButton loteInsumoButton;
    private javax.swing.JTextField loteInsumosTextField;
    private javax.swing.JLabel loteLabel;
    private javax.swing.JPanel lotePanel;
    private javax.swing.JLabel medicamentoLabel;
    private javax.swing.JPanel medicamentoPanel;
    public javax.swing.JTextField medicamento_idMedicamentoTextField;
    public javax.swing.JButton modificarAlimentoButton;
    public javax.swing.JButton modificarEnfermedadButton;
    public javax.swing.JButton modificarInsumoButton;
    public javax.swing.JButton modificarLoteButton;
    public javax.swing.JButton modificarMedicamentoButton;
    private javax.swing.JLabel nombreAlimentoLabel;
    public javax.swing.JTextField nombreAlimentoTextField;
    private javax.swing.JLabel nombreEnfermedadLabel;
    public javax.swing.JTextField nombreEnfermedadTextField;
    private javax.swing.JLabel nombreInsumoLabel;
    public javax.swing.JTextField nombreInsumoTextField;
    private javax.swing.JLabel nombreMedicamentoLabel;
    public javax.swing.JTextField nombreMedicamentoTextField;
    private javax.swing.JLabel numBultosLabel;
    public javax.swing.JTextField numBultosTextField;
    private javax.swing.JLabel numCerdosAfectLabel;
    public javax.swing.JTextField numCerdosAfectTextField;
    private javax.swing.JLabel numHembrasLabel;
    public javax.swing.JTextField numHembrasTextField;
    private javax.swing.JLabel numLoteLabel;
    private javax.swing.JLabel numMachosLabel;
    public javax.swing.JTextField numMachosTextField;
    private javax.swing.JLabel numeroExistenciasLabel;
    public javax.swing.JTextField numeroExistenciasTextField;
    private javax.swing.JLabel pesoLoteLabel;
    public javax.swing.JTextField pesoLoteTextField;
    private javax.swing.JLabel precioAlimentoLabel;
    public javax.swing.JTextField precioAlimentoTextField;
    private javax.swing.JLabel precioInsumoLabel;
    public javax.swing.JTextField precioInsumoTextField;
    private javax.swing.JLabel precioMedicamentoLabel;
    public javax.swing.JTextField precioMedicamentoTextField;
    // End of variables declaration//GEN-END:variables
}
